[file.source]
path = 'D:\Work\GIT_work\rust_excel_to_csv_conterter\excel_to_csv\example_excel\test1.xlsx'
sheets = ['onlydata', "loadsheet", "testtable"]

[file.target]
path = 'D:\Work\GIT_work\rust_excel_to_csv_conterter\excel_to_csv\example_excel\test1.csv'
separator = ','
columns = ['Col1', 'col2', 'col3']
